GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "title": "Lady",
    "name": "P",
    "message": "I hate pidgeons"
}

###
DELETE http://localhost:3000/subscribers/6295f4f966742d8cb9a06276

###
PATCH http://localhost:3000/subscribers/6294e59583b76d8a5f6768f7
Content-Type: application/json

{
    "name": "New Name"
}

